### PR TITLE
fix a typo in README

### PR DESCRIPTION
**Pull request by weakish**

### CODE REVIEW

**Comment by spywhere** [comment]
Might as well fixed the folder name in the command given.

https://github.com/mmpx12/twitter-media-downloader/blob/1f0e3eb9a9c2ab2210db98640f9769495bd91b5a/README.md?plain=1#L42

**Comment by mmpx12** [comment]
> Might as well fixed the folder name in the command given.
> 
> https://github.com/mmpx12/twitter-media-downloader/blob/1f0e3eb9a9c2ab2210db98640f9769495bd91b5a/README.md?plain=1#L42

This isnt a typo... When first write this, 3000 was the limit ... Now its arround 500-600 with up and down (x change everyday). So adding 3000 will ensure you ll have the max

**Comment by spywhere** [comment]
TBH, I don't mind if it was 3000 or 300. But the folder name `Downlaods` could be updated to `Downloads` as well. Hence the comment.

**Comment by mmpx12** [comment]
> TBH, I don't mind if it was 3000 or 300. But the folder name `Downlaods` could be updated to `Downloads` as well. Hence the comment.

Ok, so rebase to change folder name without changing -n 3000

**Comment by weakish** [comment]
> change folder name without changing -n 3000

I still changed `-n 3000` to `-n 300` because the section title of the example is "Download 300 tweets from @Spraytrains." and the sentence above the code is "it will count towards the 300".
And I also added a paragraph below for using `-n 3000` to fetch as more tweets as possible.

**Pull request merged**
